development:
  appName: "Matthew-Arbesfeld-Server"
  debug: false
  slogan: "My server"
  baseURL: "http://localhost:3000"
  apps:
    kiwi:
      name: "kiwi"
      path: "/kiwi"
      port: 3001
    poem:
      name: "poem"
      path: "/poem"
      port: 3002
    marble:
      name: "marble"
      path: "/marble"
      port: 3003
  emailFrom: 'mata@mit.edu'
  paginateNumber: 15

production:
  appName: "Matthew-Arbesfeld-Server"
  debug: false
  slogan: "My server"
  baseURL: "http://localhost:3000"
  apps:
    kiwi:
      name: "kiwi"
      path: "/kiwi"
      port: 3001
    poem:
      name: "poem"
      path: "/poem"
      port: 3002
    marble:
      name: "marble"
      path: "/marble"
      port: 3003
  emailFrom: 'mata@mit.edu'
  paginateNumber: 15
